# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SwarmBot',
            fields=[
                ('swarmBotId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='ldr',
            name='swarmBot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.SwarmBot'),
        ),
    ]
