# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swarmbot',
            name='swarmBotName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
