# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20160918_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='swarmbot',
            name='patchStatus',
            field=models.BooleanField(default=False),
        ),
    ]
