# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_swarmbot_patchstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='IR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irId', models.IntegerField()),
                ('irReading', models.IntegerField()),
                ('swarmBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.SwarmBot')),
            ],
        ),
        migrations.CreateModel(
            name='US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usId', models.IntegerField()),
                ('usReading', models.IntegerField()),
                ('swarmBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.SwarmBot')),
            ],
        ),
    ]
