# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_ir_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='DS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsId', models.IntegerField()),
                ('dsReading', models.IntegerField()),
                ('swarmBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.SwarmBot')),
            ],
        ),
        migrations.RemoveField(
            model_name='us',
            name='swarmBot',
        ),
        migrations.DeleteModel(
            name='US',
        ),
    ]
