# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20161128_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ds',
            name='swarmBot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.SwarmBot'),
        ),
    ]
