# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20161128_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ds',
            name='reading',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ir',
            name='reading',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ldr',
            name='reading',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
