# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20161129_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldr',
            name='swarmBot',
        ),
        migrations.AlterField(
            model_name='ir',
            name='reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ir',
            name='swarmBot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.SwarmBot'),
        ),
        migrations.DeleteModel(
            name='LDR',
        ),
    ]
