# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_swarmbot_swarmbotname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldr',
            name='reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
