# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20161108_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ds',
            old_name='dsReading',
            new_name='reading',
        ),
        migrations.RenameField(
            model_name='ir',
            old_name='irReading',
            new_name='reading',
        ),
    ]
