# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20161128_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldr',
            name='ldrId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
