# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_ldr_ldrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldr',
            name='reading',
            field=models.BooleanField(default=None),
        ),
    ]
